name: Test and Deploy result from Python
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Start containers
        run: |
          sudo apt install make
          make pull
          docker-compose -f "docker-compose.yml" up -d

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest -v --tb=line --alluredir=reports -n 5 -q

      - name: Generate report
        if: always()
        run: |
          sudo mkdir /allure
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.tgz
          sudo tar zxf allure-2.17.2.tgz -C /allure
          export PATH="/allure/allure-2.17.2/bin:${PATH}"
          allure generate reports

      - name: Stop containers
        if: always()
        run: |
          docker-compose -f "docker-compose.yml" down -rm
          make clean

      - name: Deploy report🚀
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: allure-report
          clean: false
